[connect.py]
  [test_bidi_session_3[capabilities0-True\]]
    expected: ERROR

  [test_websocket_url_connect[capabilities0\]]
    expected: ERROR

  [test_bidi_session_1[True\]]
    expected: ERROR

  [test_bidi_session_2[True\]]
    expected: ERROR

